import { productions } from '../src/dsl';
import { generateCstDts } from 'chevrotain';
import * as path from 'node:path';
import * as fs from 'node:fs';
import process from 'node:process';

function generateChevrotainDts(): void {
    const generatedFile = path.resolve(__dirname, '../src/generated/chevrotain_dts.ts');
    console.log(`Will generate the file ${generatedFile}`);

    const content =
        `// This file is autogenerated using "npm run generate".\n` +
        `// Don\'t edit this file manually.\n\n` +
        generateCstDts(productions);
    try {
        fs.writeFileSync(generatedFile, content);
        console.log(`Wrote to ${generatedFile}`);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}

generateChevrotainDts();

// 'export {}' statement to make it a module to be able to run using `npm run generate`
export {};
