import { productions, serializedGrammar } from '../frontend/dsl';
import { generateCstDts, createSyntaxDiagramsCode } from 'chevrotain';
import * as path from 'node:path';
import * as fs from 'node:fs';
import process from 'node:process';

function generateChevrotainDts(): void {
    const generatedFile = path.resolve(__dirname, '../frontend/generated/chevrotain_dts.ts');
    console.log(`Will generate the file ${generatedFile}`);

    const content =
        `// This file is autogenerated using "npm run generate".\n` +
        `// Don\'t edit this file manually.\n\n` +
        generateCstDts(productions);
    try {
        fs.writeFileSync(generatedFile, content);
        console.log(`Wrote to ${generatedFile}`);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}

function generateSyntaxDiagram(): void {
    const htmlText = createSyntaxDiagramsCode(serializedGrammar);
    const diagramFile = path.resolve(__dirname, '../public/syntax_diagram.html');
    try {
        fs.writeFileSync(diagramFile, htmlText);
        console.log(`Wrote to ${diagramFile}`);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}

generateChevrotainDts();
generateSyntaxDiagram();

// 'export {}' statement to make it a module to be able to run using `npm run generate`
export {};
